const map=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
function mlink(label,q,cls='map'){return `<a class="${cls}" target="_blank" rel="noopener" href="${map(q||label)}">${label}</a>`;}
function syncActiveDay(){const id=(location.hash||'#d1').slice(1);document.querySelectorAll('[data-day-link]').forEach(a=>a.classList.toggle('primary',a.dataset.dayLink===id));document.querySelectorAll('.day-section').forEach(s=>s.classList.toggle('is-active',s.id===id));}
function dayNav(days){return `<div class="daynav">${days.map(d=>`<a class="btn datebtn" data-day-link="${d.id}" href="#${d.id}"><span>${d.day}</span><b>${d.shortDate}（${d.weekday}）</b></a>`).join('')}</div>`;}
function stepCard(s){return `<div class="step"><div class="time">${s.time}</div><b>${s.title}</b><p class="why">${s.why}</p><div class="route">${s.route.map(x=>`<span>${x}</span>`).join('')}</div>${mlink('🎯 終點：'+s.dest,s.map,'map dest')}</div>`;}
function backupCard(b){return `<div class="card"><span class="tag local">${b.title}</span><div>${b.items.map(x=>mlink(x,x)).join('')}</div></div>`;}
function renderItinerary(){const data=KYOTO_ITINERARY;document.body.insertAdjacentHTML('afterbegin',`<header class="top"><h1>🌸 樂京都 2026｜每日行程</h1><div class="small">日期醒目版｜點日期會高亮該日，方便確認現在看的是 7 月幾號</div><div class="nav"><a class="btn" href="index.html">總目錄</a><a class="btn primary" href="itinerary.html">每日行程</a><a class="btn" href="transport.html">交通與行李</a></div><div class="label">按日期跳轉</div>${dayNav(data.days)}</header>`);
const lodging=`<section class="card"><span class="tag near">住宿基準</span><h2>0｜住宿</h2><h3>${data.lodging.name}</h3><p class="note">${data.lodging.period}。${data.lodging.note}</p>${mlink('🎯 飯店：'+data.lodging.name,data.lodging.map,'map dest')}</section>`;
const days=data.days.map(d=>`<section class="day-section" id="${d.id}"><div class="date-hero"><div><span class="tag">${d.day}</span><h2>${d.shortDate}（${d.weekday}）｜${d.title}</h2></div><div class="date-chip">${d.shortDate}</div></div><div class="card"><span class="tag">今日摘要</span><p class="note">${d.summary}</p></div><h3>主行程</h3><div class="card">${d.steps.map(stepCard).join('')}</div><h3>就地備選</h3><div class="cols">${d.backups.map(backupCard).join('')}</div></section>`).join('');
document.querySelector('main').innerHTML=lodging+days+'<a class="back" href="#">↑ 上方</a>';syncActiveDay();}
document.addEventListener('DOMContentLoaded',renderItinerary);window.addEventListener('hashchange',syncActiveDay);