const map=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const WEATHER=window.KYOTO_ITINERARY_WEATHER;
const WEATHER_DAILY='weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,precipitation_probability_max,precipitation_sum,uv_index_max,wind_speed_10m_max';
const WEATHER_REFRESH_MS=(WEATHER?.refreshHours||4)*60*60*1000;
const JST_OFFSET_MS=9*60*60*1000;
const WEATHER_CODES={0:['☀️','晴朗'],1:['🌤️','大致晴朗'],2:['⛅','局部多雲'],3:['☁️','陰天'],45:['🌫️','霧'],48:['🌫️','霧淞'],51:['🌦️','輕微毛毛雨'],53:['🌦️','毛毛雨'],55:['🌧️','較強毛毛雨'],56:['🌧️','凍毛毛雨'],57:['🌧️','強凍毛毛雨'],61:['🌦️','小雨'],63:['🌧️','中雨'],65:['🌧️','大雨'],66:['🌧️','凍雨'],67:['🌧️','強凍雨'],71:['🌨️','小雪'],73:['🌨️','中雪'],75:['❄️','大雪'],77:['🌨️','雪粒'],80:['🌦️','局部陣雨'],81:['🌧️','陣雨'],82:['⛈️','強陣雨'],85:['🌨️','局部陣雪'],86:['❄️','強陣雪'],95:['⛈️','雷雨'],96:['⛈️','雷雨伴小冰雹'],99:['⛈️','雷雨伴大冰雹']};
function mlink(label,q,cls='map'){return `<a class="${cls}" target="_blank" rel="noopener" href="${map(q||label)}">${label}</a>`;}
function setActiveDay(id){document.querySelectorAll('[data-day-link]').forEach(a=>a.classList.toggle('primary',a.dataset.dayLink===id));document.querySelectorAll('.day-section').forEach(s=>s.classList.toggle('is-active',s.id===id));}
function syncActiveDay(){setActiveDay((location.hash||'#d1').slice(1));}
function dayNav(days){return `<div class="daynav">${days.map(d=>`<a class="btn datebtn" data-day-link="${d.id}" href="#${d.id}"><span>${d.day}</span><b>${d.dateText}</b></a>`).join('')}</div>`;}
function routeChip(x){if(typeof x==='string')return `<span>${x}</span>`;const label=x.label||x.name||'';return x.map?mlink(label,x.map,'route-link'):`<span>${label}</span>`;}
function stepCard(s){return `<div class="step"><div class="time">${s.time}</div><b>${s.title}</b><p class="why">${s.why}</p><div class="route">${s.route.map(routeChip).join('')}</div>${mlink('🎯 終點：'+s.dest,s.map,'map dest')}</div>`;}
function backupCard(b){return `<div class="card"><span class="tag local">${b.title}</span><div>${b.items.map(x=>mlink(x,x)).join('')}</div></div>`;}
function setupDayClicks(){document.querySelectorAll('[data-day-link]').forEach(a=>a.addEventListener('click',()=>setActiveDay(a.dataset.dayLink)));}
function setupDayObserver(){if(!('IntersectionObserver' in window))return;const io=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActiveDay(visible.target.id);},{rootMargin:'-30% 0px -55% 0px',threshold:[0,.25,.5,.75,1]});document.querySelectorAll('.day-section').forEach(s=>io.observe(s));}
function weatherSlot(){return Math.floor((Date.now()+JST_OFFSET_MS)/WEATHER_REFRESH_MS);}
function nextWeatherUpdate(){const shifted=Date.now()+JST_OFFSET_MS;return Date.now()+(WEATHER_REFRESH_MS-(shifted%WEATHER_REFRESH_MS));}
function formatJapanTime(value){return new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value));}
function weatherApiUrl(location){const p=new URLSearchParams({latitude:String(location.latitude),longitude:String(location.longitude),daily:WEATHER_DAILY,timezone:WEATHER.timezone,past_days:'7',forecast_days:'16'});return 'https://api.open-meteo.com/v1/forecast?'+p.toString();}
async function fetchLocationWeather(key,force=false){const location=WEATHER.locations[key];if(!location)throw new Error('找不到天氣地點');const slot=weatherSlot();const cacheKey=`kyoto-weather-v2:${key}:${slot}`;if(!force){try{const cached=JSON.parse(localStorage.getItem(cacheKey)||'null');if(cached?.data)return cached;}catch(error){}}
 const response=await fetch(weatherApiUrl(location),{cache:'no-store'});if(!response.ok)throw new Error(`天氣服務 ${response.status}`);const payload={fetchedAt:Date.now(),data:await response.json()};try{localStorage.setItem(cacheKey,JSON.stringify(payload));}catch(error){}return payload;}
function weatherForDate(payload,date){const daily=payload.data?.daily;const index=daily?.time?.indexOf(date)??-1;if(index<0)return null;const value=name=>daily[name]?.[index];return {code:value('weather_code'),max:value('temperature_2m_max'),min:value('temperature_2m_min'),feels:value('apparent_temperature_max'),rainChance:value('precipitation_probability_max'),rain:value('precipitation_sum'),uv:value('uv_index_max'),wind:value('wind_speed_10m_max')};}
function weatherSeverity(w){const rain=Number(w.rainChance||0),feels=Number(w.feels||0),uv=Number(w.uv||0),wind=Number(w.wind||0),code=Number(w.code||0);if(code>=95||rain>=70||wind>=35)return 'storm';if(rain>=45)return 'rain';if(feels>=35||uv>=9)return 'hot';return 'ok';}
function weatherBadges(w){const badges=[];if(Number(w.rainChance)>=45)badges.push('雨具');if(Number(w.feels)>=35)badges.push('高溫');if(Number(w.uv)>=8)badges.push('防曬');if(Number(w.wind)>=30)badges.push('強風');return badges.length?badges:['可照原案'];}
function tripAdvice(day,w,place){const severity=weatherSeverity(w);const base={d1:'奈良戶外比例高，先做奈良公園、東大寺；午後保留奈良國立博物館、奈良ホテル或早回京都。',d2:'清水寺與東山坡道多，上午先完成清水寺、三年坂；午後用高島屋、大丸與祇園甘味避暑。',d3:'南禪寺與岡崎可早出。午後熱或雨時切到京セラ美術館、近代美術館、京都岡崎 蔦屋書店。',d4:'宇治若熱或雨，平等院鳳翔館與茶店優先；午後可提早回京都站伊勢丹。',d5:'七條線室內備案多；雨天把京都國立博物館、河井寛次郎記念館、Kaikado Café提前。',d6:'最後一天以大丸或高島屋為主。若機場風雨偏強，提早往京都站與關西機場移動。'}[day.id]||'依天氣調整室內與戶外比例。';
 if(severity==='storm')return `${place}：天氣風險高。${base}`;
 if(severity==='rain')return `${place}：有雨勢機率。${base}`;
 if(severity==='hot')return `${place}：高溫或紫外線偏強。${base}`;
 return `${place}：天氣可照原案，但仍保留午後室內備案。`;
}
function weatherCard(location,payload,day){const w=weatherForDate(payload,day.date);if(!w)return {html:`<article class="weather-error">${location.name}：尚無 ${day.date} 預報。</article>`,severity:'unknown'};const code=WEATHER_CODES[w.code]||['🌡️','天氣狀況'];const severity=weatherSeverity(w);const badges=weatherBadges(w).map(x=>`<span>${x}</span>`).join('');const html=`<article class="weather-card weather-${severity}"><div class="weather-top"><div><div class="weather-place">${location.name}</div><div class="weather-badges">${badges}</div></div><div class="weather-icon">${code[0]}</div></div><div class="weather-main"><strong>${Math.round(w.max)}°／${Math.round(w.min)}°</strong><span>${code[1]}・體感 ${Math.round(w.feels)}°</span></div><div class="weather-stats"><span>降雨 ${Math.round(w.rainChance||0)}%</span><span>雨量 ${Number(w.rain||0).toFixed(1)} mm</span><span>UV ${Number(w.uv||0).toFixed(1)}</span><span>風 ${Math.round(w.wind||0)} km/h</span></div><p class="weather-advice"><b>行程建議：</b>${tripAdvice(day,w,location.name)}</p><div class="weather-meta">更新：${formatJapanTime(payload.fetchedAt)}｜下次：約 ${formatJapanTime(nextWeatherUpdate())}｜<a class="weather-source" href="${WEATHER.source.url}" target="_blank" rel="noopener">${WEATHER.source.name}</a></div></article>`;return {html,severity};}
function markDayWeather(dayId,severities){const section=document.getElementById(dayId);if(!section)return;section.classList.remove('weather-ok-day','weather-hot-day','weather-rain-day','weather-storm-day');const rank={unknown:0,ok:1,hot:2,rain:3,storm:4};const top=severities.sort((a,b)=>(rank[b]||0)-(rank[a]||0))[0]||'unknown';if(top!=='unknown')section.classList.add(`weather-${top}-day`);}
async function refreshWeatherDay(dayId,force=false){const day=window.KYOTO_ITINERARY?.days?.find(x=>x.id===dayId);const target=document.getElementById(`weather-${dayId}`);if(!day||!target||!WEATHER)return;const keys=WEATHER.days[dayId]||[];target.innerHTML='<div class="weather-loading">正在取得最新天氣預報…</div>';const results=await Promise.all(keys.map(async key=>{const location=WEATHER.locations[key];try{return weatherCard(location,await fetchLocationWeather(key,force),day);}catch(error){return {html:`<article class="weather-error">${location?.name||key}：天氣載入失敗。<button class="weather-refresh" type="button" data-weather-retry="${dayId}">重新載入</button></article>`,severity:'unknown'};}}));markDayWeather(dayId,results.map(x=>x.severity));target.innerHTML=`<div class="weather-heading"><h3>最新天氣預報</h3><button class="weather-refresh" type="button" data-weather-refresh="${dayId}">立即更新</button></div><div class="weather-grid">${results.map(x=>x.html).join('')}</div>`;target.querySelectorAll('[data-weather-refresh],[data-weather-retry]').forEach(button=>button.addEventListener('click',()=>refreshWeatherDay(dayId,true)));}
function refreshAllWeather(force=false){if(!WEATHER)return;window.KYOTO_ITINERARY.days.forEach(day=>refreshWeatherDay(day.id,force));}
function scheduleWeatherRefresh(){if(!WEATHER)return;const delay=Math.max(1000,nextWeatherUpdate()-Date.now()+2000);setTimeout(()=>{refreshAllWeather(true);setInterval(()=>refreshAllWeather(true),WEATHER_REFRESH_MS);},delay);}
function renderItinerary(){const data=window.KYOTO_ITINERARY;document.body.insertAdjacentHTML('afterbegin',`<header class="top"><h1>🌸 樂京都 2026｜每日行程</h1><div class="small">天氣智慧版｜每 4 小時更新一次（每日 6 次）｜地點節點可點 Google Maps</div><div class="nav"><a class="btn" href="index.html">總目錄</a><a class="btn primary" href="itinerary.html">每日行程</a><a class="btn" href="transport.html">交通與行李</a></div><div class="label">按日期跳轉</div>${dayNav(data.days)}</header>`);
 const lodging=`<section class="card"><span class="tag near">住宿基準</span><h2>0｜住宿</h2><h3>${data.lodging.name}</h3><p class="note">${data.lodging.period}。${data.lodging.note}</p>${mlink('🎯 飯店：'+data.lodging.name,data.lodging.map,'map dest')}</section>`;
 const days=data.days.map(d=>`<section class="day-section" id="${d.id}" data-date="${d.date}"><div class="date-hero"><div><span class="tag">${d.day}</span><h2><span class="date-title">${d.dateText}</span>｜${d.title}</h2></div><div class="date-chip"><small>7月</small><b>${d.shortDate.split('/')[1]}日</b></div></div><div class="weather-day" id="weather-${d.id}"><div class="weather-loading">準備天氣資料…</div></div><div class="card"><span class="tag">今日摘要</span><p class="note">${d.summary}</p></div><h3>主行程</h3><div class="card">${d.steps.map(stepCard).join('')}</div><h3>就地備選</h3><div class="cols">${d.backups.map(backupCard).join('')}</div></section>`).join('');
 document.querySelector('main').innerHTML=lodging+days+'<a class="back" href="#">↑ 上方</a>';setupDayClicks();syncActiveDay();setupDayObserver();refreshAllWeather();scheduleWeatherRefresh();}
window.refreshWeatherDay=refreshWeatherDay;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',renderItinerary);else renderItinerary();
window.addEventListener('hashchange',syncActiveDay);
