const DB=window.KYOTO_PLACES;
const T=DB.themes?.must_go;
const TYPE_ORDER=['books','food','drinks','shops','sights'];
const map=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const label=k=>DB.categories[k]?.label||k;
const mlink=(txt,q)=>`<a class="map" target="_blank" rel="noopener" href="${map(q||txt)}">${txt}</a>`;
function header(){return `<header class="top"><h1>🌸 樂京都 2026</h1><div class="small">唯一入口：t202607/index.html｜資料模型：KYOTO_THEMES.must_go → KYOTO_PLACES</div><div class="nav"><a class="btn" href="index.html">總目錄</a><a class="btn" href="itinerary.html">每日行程</a><a class="btn" href="transport.html">交通與行李</a><a class="btn primary" href="theme-must-go.html">本次必去</a><a class="btn" href="theme-hotel-nearby.html">飯店附近</a><a class="btn" href="theme-beef-tongue.html">牛肉牛舌</a><a class="btn" href="theme-old-coffee-tea.html">老咖啡老茶舖</a><a class="btn" href="type-books.html">書店</a></div></header>`;}
function items(){return (T.sections||[]).flatMap(s=>(s.items||[]).map(x=>({...x,sectionTitle:s.title})));}
function card(x){const a=DB.areas.find(v=>v.id===x.area);const use=x.category==='food'?'正餐／西餐':x.category==='drinks'?'咖啡／茶':x.category==='books'?'書店／古書':'景點／建築';return `<article class="place-card card"><div><span class="tag pick">主題：本次必去</span><span class="tag">${x.typeLabel}</span><span class="tag muted">地區：${a?.label||x.area}</span></div><h3>${x.name}</h3><p class="why"><b>用途：</b>${use}</p><p class="note">${x.note}</p><div>${mlink('📍 Google Maps',x.map||x.mapQuery||x.name)}</div></article>`;}
function boot(){if(!DB||!T){document.querySelector('main').innerHTML='<section class="card"><h2>資料尚未載入</h2></section>';return;}document.body.insertAdjacentHTML('afterbegin',header());const xs=items();const areaGroups=DB.areas.map(a=>[a,xs.filter(x=>x.area===a.id)]).filter(([,v])=>v.length);const typeGroups=TYPE_ORDER.filter(k=>xs.some(x=>x.category===k)).map(k=>[k,xs.filter(x=>x.category===k)]);const areaNav=areaGroups.map(([a,v])=>`<a class="btn" href="#area-${a.id}">${a.label} ${v.length}</a>`).join('');const typeNav=typeGroups.map(([k,v])=>`<a class="btn" href="#type-${k}">${label(k)} ${v.length}</a>`).join('');const areaSections=areaGroups.map(([a,v])=>`<section class="typeblock" id="area-${a.id}"><h2>${a.label} <span class="small">${v.length} 筆</span></h2><div class="placegrid">${v.map(card).join('')}</div></section>`).join('');const typeSections=typeGroups.map(([k,v])=>`<section class="typeblock" id="type-${k}"><h2>${label(k)} <span class="small">${v.length} 筆</span></h2><div class="placegrid">${v.map(card).join('')}</div></section>`).join('');document.querySelector('main').innerHTML=`<section class="hero-card card"><span class="tag pick">主題頁</span><h2>${T.title}</h2><p class="note">${T.lead}</p><div class="statbar"><span>${xs.length} 筆</span><span>${areaGroups.length} 個地區</span><span>${typeGroups.length} 種類型</span></div>${mlink('📍 地圖基準：四条烏丸',T.base.map)}</section><h2>依地區分類</h2><div class="nav localnav">${areaNav}</div>${areaSections}<h2>依類型分類</h2><div class="nav localnav">${typeNav}</div>${typeSections}<a class="back" href="#">↑ 上方</a>`;}
document.addEventListener('DOMContentLoaded',boot);
