const DB=window.KYOTO_PLACES;
const TYPE_ORDER=['books','food','drinks','shops','shinise','heritage','sights'];
const TYPE_PAGES={books:'type-books.html',food:'type-food.html',drinks:'type-drinks.html',shops:'type-shops.html',shinise:'type-shinise.html',heritage:'type-heritage.html',sights:'type-sights.html'};
const THEME_PAGES={hotel_nearby:'theme-hotel-nearby.html',beef_tongue:'theme-beef-tongue.html',old_coffee_tea:'theme-old-coffee-tea.html'};
const map=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const label=k=>DB.categories[k]?.label||k;
const mlink=(label,q,cls='map')=>`<a class="${cls}" target="_blank" rel="noopener" href="${map(q||label)}">${label}</a>`;
function matchKind(p,k){if(k==='shinise')return p.flags?.shinise;if(k==='heritage')return p.flags?.heritage;return p.category===k;}
function sortPlaces(a){const r={high:0,normal:1,low:2};return [...a].sort((x,y)=>(r[x.priority]??1)-(r[y.priority]??1)||x.name.localeCompare(y.name,'ja'));}
const placesByArea=(a,k)=>sortPlaces(DB.places.filter(p=>p.area===a&&matchKind(p,k)));
const placesByType=k=>sortPlaces(DB.places.filter(p=>matchKind(p,k)));
const typeListForArea=a=>TYPE_ORDER.filter(k=>placesByArea(a,k).length);
function tagClass(p){const t=`${p.typeLabel} ${p.description}`;if(t.includes('飯店')||t.includes('車站'))return 'near';if(p.flags?.shinise||t.includes('古書')||t.includes('老舖')||t.includes('町家')||t.includes('老屋'))return 'old';if(p.flags?.heritage||t.includes('近代')||t.includes('洋風'))return 'western';return '';}
function themeTags(p){return (p.themeLabels||[]).map(t=>`<span class="tag pick">主題：${t}</span>`).join('');}
function placeCard(p){const high=p.priority==='high'?'<span class="tag pick">優先</span>':'';return `<article class="place-card card"><div>${high}${themeTags(p)}<span class="tag ${tagClass(p)}">${p.typeLabel}</span><span class="tag muted">地區：${p.areaLabel}</span></div><h3>${p.name}</h3><p class="why"><b>定位：</b>${p.categoryLabel}${p.flags?.shinise?'／老舖':''}${p.flags?.heritage?'／建築古蹟':''}</p><p class="note">${p.description||p.summary||'順路備案。'}</p><div>${mlink('📍 Google Maps',p.mapQuery||p.name)}</div></article>`;}
function themeItemCard(x,t){const a=DB.areas.find(v=>v.id===x.area);return `<article class="place-card card"><div><span class="tag pick">主題：${t}</span><span class="tag ${x.category==='hotel'?'near':''}">${x.typeLabel}</span><span class="tag muted">地區：${a?.label||x.area}</span></div><h3>${x.name}</h3><p class="why"><b>用途：</b>${x.category==='food'?'正餐／補食':x.category==='drinks'?'咖啡／甜點':'採買／景點'}</p><p class="note">${x.note}</p><div>${mlink('📍 Google Maps',x.map||x.name)}</div></article>`;}
function header(active=''){return `<header class="top"><h1>🌸 樂京都 2026</h1><div class="small">唯一入口：t202607/index.html｜資料模型：地點物件化</div><div class="nav"><a class="btn ${active==='index'?'primary':''}" href="index.html">總目錄</a><a class="btn" href="itinerary.html">每日行程</a><a class="btn" href="transport.html">交通與行李</a><a class="btn ${active==='hotel_nearby'?'primary':''}" href="theme-hotel-nearby.html">飯店附近</a><a class="btn ${active==='beef_tongue'?'primary':''}" href="theme-beef-tongue.html">牛肉牛舌</a><a class="btn ${active==='old_coffee_tea'?'primary':''}" href="theme-old-coffee-tea.html">老咖啡老茶舖</a><a class="btn ${active==='books'?'primary':''}" href="type-books.html">書店</a></div></header>`;}
function statLine(){return `<div class="statbar"><span>${DB.places.length} 筆地點</span><span>${DB.areas.length} 個地區</span><span>7 種類型</span></div>`;}
function renderIndex(){document.body.insertAdjacentHTML('afterbegin',header('index'));const hero=`<section class="hero-card card"><span class="tag pick">京都旅遊手帳</span><h2>樂京都 2026｜總控制台</h2><p class="note">首頁只放入口與判斷。地點內容統一從 <b>KYOTO_PLACES</b> 物件資料模型渲染；主題頁另由 <b>KYOTO_THEMES</b> 管理。</p>${statLine()}<div class="quickgrid"><a class="bigbtn" href="itinerary.html">每日行程<span>7/9–7/13</span></a><a class="bigbtn" href="transport.html">交通與行李<span>公開版</span></a><a class="bigbtn" href="theme-hotel-nearby.html">飯店附近<span>早餐・咖啡・晚餐・錦市場</span></a><a class="bigbtn" href="theme-beef-tongue.html">牛肉／牛舌<span>牛舌・燒肉・壽喜燒</span></a><a class="bigbtn" href="theme-old-coffee-tea.html">老咖啡老茶舖<span>老喫茶・茶舖・町家茶寮</span></a><a class="bigbtn" href="type-books.html">書店／古書店<span>新書・古書・選書</span></a></div></section>`;
const themeRows=Object.values(DB.themes||{}).map(t=>`<a class="card linkcard" href="${THEME_PAGES[t.id]||'#'}"><span class="tag pick">主題頁</span><h3>${t.title}</h3><p class="note">${t.lead}</p></a>`).join('');
const typeRows=TYPE_ORDER.map(k=>`<a class="card linkcard" href="${TYPE_PAGES[k]}"><span class="tag">依類型</span><h3>${label(k)}</h3><p class="note">${placesByType(k).length} 筆，先類型再地區。</p></a>`).join('');
const areaRows=DB.areas.map(a=>`<a class="card linkcard" href="${a.id}.html"><span class="tag">依地區</span><h3>${a.label}</h3><p class="note">${a.title}<br>${TYPE_ORDER.map(k=>`${label(k)} ${placesByArea(a.id,k).length}`).filter(x=>!x.endsWith(' 0')).join('・')}</p></a>`).join('');
document.querySelector('main').innerHTML=`${hero}${themeRows?'<h2 id="themes">主題頁</h2><div class="grid">'+themeRows+'</div>':''}<h2 id="types">依類型找</h2><div class="grid">${typeRows}</div><h2 id="areas">依地區找</h2><div class="grid">${areaRows}</div>`;}
function renderArea(id){const area=DB.areas.find(a=>a.id===id);document.body.insertAdjacentHTML('afterbegin',header(id));const keys=typeListForArea(id);const all=keys.flatMap(k=>placesByArea(id,k));const featured=sortPlaces(all).filter((p,i)=>p.priority==='high'||i<5).slice(0,5);const nav=`<div class="nav localnav">${keys.map(k=>`<a class="btn" href="#${k}">${label(k)} ${placesByArea(id,k).length}</a>`).join('')}</div>`;const sections=keys.map(k=>`<section class="typeblock" id="${k}"><h2>${label(k)} <span class="small">${placesByArea(id,k).length} 筆</span></h2><div class="placegrid">${placesByArea(id,k).map(placeCard).join('')}</div></section>`).join('');document.querySelector('main').innerHTML=`<section class="hero-card card"><span class="tag pick">地區</span><h2>${area.title}</h2><p class="note">${area.lead||'本區地點依類型分組；同一地點可同時出現在老舖、建築、書店等分類。'}</p>${statLine()}<a class="map" href="index.html">回總目錄</a></section><h2>本區優先</h2><div class="placegrid featured">${featured.map(placeCard).join('')}</div>${nav}${sections}<a class="back" href="#">↑ 上方</a>`;}
function groupByArea(list){return DB.areas.map(a=>[a,sortPlaces(list.filter(p=>p.area===a.id))]).filter(([,items])=>items.length);}
function renderType(kind){if(kind==='books')return renderBooks();document.body.insertAdjacentHTML('afterbegin',header(kind));const list=placesByType(kind);const groups=groupByArea(list);const nav=`<div class="nav localnav">${groups.map(([a,items])=>`<a class="btn" href="#${a.id}">${a.label} ${items.length}</a>`).join('')}</div>`;const sections=groups.map(([a,items])=>`<section class="typeblock" id="${a.id}"><h2>${a.label} <span class="small">${items.length} 筆</span></h2><div class="placegrid">${items.map(placeCard).join('')}</div></section>`).join('');document.querySelector('main').innerHTML=`<section class="hero-card card"><span class="tag pick">依類型找</span><h2>${label(kind)}</h2><p class="note">先看類型，再依地區分組。內容可與地區頁重複，因為同一個地點可能同時是老舖、建築或景點。</p><div class="statbar"><span>${list.length} 筆</span><span>${groups.length} 區</span></div><a class="map" href="index.html">回總目錄</a></section>${nav}${sections}<a class="back" href="#">↑ 上方</a>`;}
function routeCard(r){return `<article class="route-card card"><span class="tag pick">實用路線</span><h3>${r.title}</h3><div class="routechips">${r.items.map((x,i)=>`<span>${i+1}. ${x}</span>`).join('')}</div><p class="note">當成移動順序參考，不代表每一站都必進。</p></article>`;}
function priorityCard(g){return `<article class="route-card card"><span class="tag pick">優先</span><h3>${g.title}</h3><div>${g.items.map(x=>mlink(x,x)).join('')}</div></article>`;}
function renderBooks(){document.body.insertAdjacentHTML('afterbegin',header('books'));const d=DB;const priority=`<h2>${d.bookPriority.title}</h2><div class="grid">${d.bookPriority.groups.map(priorityCard).join('')}</div>`;const routes=`<h2>你的實用路線</h2><div class="grid">${d.bookRoutes.map(routeCard).join('')}</div>`;const nav=`<div class="nav localnav">${d.bookSections.map(s=>`<a class="btn" href="#${s.id}">${s.title}</a>`).join('')}</div>`;const sections=d.bookSections.map(s=>{const items=sortPlaces(d.places.filter(p=>p.category==='books'&&p.bookSection===s.id));return `<section class="typeblock" id="${s.id}"><h2>${s.title} <span class="small">${items.length} 筆</span></h2><div class="card"><p class="note">${s.lead}</p></div><div class="placegrid">${items.map(placeCard).join('')}</div></section>`;}).join('');document.querySelector('main').innerHTML=`<section class="hero-card card"><span class="tag pick">書店正本資料</span><h2>京都書店／古書店</h2><p class="note">依京都觀光會走到的區域整理新書、古書、選書店。這頁由統一地點物件資料渲染。</p><div class="statbar"><span>${placesByType('books').length} 筆書店</span><span>${d.bookSections.length} 個書店區</span></div><a class="map" href="index.html">回總目錄</a></section>${nav}${priority}${routes}${sections}<a class="back" href="#">↑ 上方</a>`;}
function renderTheme(id){const t=DB.themes?.[id];document.body.insertAdjacentHTML('afterbegin',header(id));if(!t){document.querySelector('main').innerHTML='<section class="card"><h2>找不到主題資料</h2></section>';return;}const total=t.sections.reduce((n,s)=>n+s.items.length,0);const nav=`<div class="nav localnav">${t.sections.map(s=>`<a class="btn" href="#${s.id}">${s.title} ${s.items.length}</a>`).join('')}</div>`;const sections=t.sections.map(s=>`<section class="typeblock" id="${s.id}"><h2>${s.title} <span class="small">${s.items.length} 筆</span></h2><div class="card"><p class="note">${s.lead}</p></div><div class="placegrid">${s.items.map(x=>themeItemCard(x,t.title)).join('')}</div></section>`).join('');document.querySelector('main').innerHTML=`<section class="hero-card card"><span class="tag pick">主題頁</span><h2>${t.title}</h2><p class="note">${t.lead}</p><div class="statbar"><span>${total} 筆</span><span>${t.sections.length} 類</span><span>基準：${t.base.name}</span></div>${mlink('📍 飯店基準點',t.base.map)}</section>${nav}${sections}<a class="back" href="#">↑ 上方</a>`;}
function boot(){if(!DB){document.querySelector('main').innerHTML='<div class="card"><h2>資料尚未載入</h2></div>';return;}if(window.PAGE_THEME)return renderTheme(window.PAGE_THEME);if(window.PAGE_AREA)return renderArea(window.PAGE_AREA);if(window.PAGE_KIND)return renderType(window.PAGE_KIND);renderIndex();}
document.addEventListener('DOMContentLoaded',boot);