const DB=window.KYOTO_PLACES;
const TYPE_ORDER=['books','food','drinks','shops','shinise','heritage','sights'];
const TYPE_PAGES={books:'type-books.html',food:'type-food.html',drinks:'type-drinks.html',shops:'type-shops.html',shinise:'type-shinise.html',heritage:'type-heritage.html',sights:'type-sights.html'};
const THEME_PAGES={must_go:'theme-must-go.html',hotel_nearby:'theme-hotel-nearby.html',beef_tongue:'theme-beef-tongue.html',old_coffee_tea:'theme-old-coffee-tea.html'};
const map=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const label=k=>DB.categories[k]?.label||k;
const mlink=(txt,q,cls='map')=>`\u003ca class="${cls}" target="_blank" rel="noopener" href="${map(q||txt)}">${txt}\u003c/a>`;
function esc(s){return String(s??'');}
function matchKind(p,k){if(k==='shinise')return p.flags?.shinise;if(k==='heritage')return p.flags?.heritage;return p.category===k;}
function sortPlaces(a){const r={high:0,normal:1,low:2};return [...a].sort((x,y)=>(r[x.priority]??1)-(r[y.priority]??1)||x.name.localeCompare(y.name,'ja'));}
const placesByArea=(a,k)=>sortPlaces(DB.places.filter(p=>p.area===a&&matchKind(p,k)));
const placesByType=k=>sortPlaces(DB.places.filter(p=>matchKind(p,k)));
const typeListForArea=a=>TYPE_ORDER.filter(k=>placesByArea(a,k).length);
function tagClass(p){const t=`${p.typeLabel} ${p.description}`;if(t.includes('飯店')||t.includes('車站'))return 'near';if(p.flags?.shinise||t.includes('古書')||t.includes('老舖')||t.includes('町家')||t.includes('老屋'))return 'old';if(p.flags?.heritage||t.includes('近代')||t.includes('洋風'))return 'western';return '';}
function themeTags(p){return (p.themeLabels||[]).map(t=>`\u003cspan class="tag pick">主題：${esc(t)}\u003c/span>`).join('');}
function placeCard(p){const high=p.priority==='high'?`\u003cspan class="tag pick">優先\u003c/span>`:'';return `\u003carticle class="place-card card">\u003cdiv>${high}${themeTags(p)}\u003cspan class="tag ${tagClass(p)}">${esc(p.typeLabel)}\u003c/span>\u003cspan class="tag muted">地區：${esc(p.areaLabel)}\u003c/span>\u003c/div>\u003ch3>${esc(p.name)}\u003c/h3>\u003cp class="why">\u003cb>定位：\u003c/b>${esc(p.categoryLabel)}${p.flags?.shinise?'／老舖':''}${p.flags?.heritage?'／建築古蹟':''}\u003c/p>\u003cp class="note">${esc(p.description||p.summary||'順路備案。')}\u003c/p>\u003cdiv>${mlink('📍 Google Maps',p.mapQuery||p.name)}\u003c/div>\u003c/article>`;}
function themeItemCard(x,t){const a=DB.areas.find(v=>v.id===x.area);const use=x.category==='food'?'正餐／補食':x.category==='drinks'?'咖啡／甜點':x.category==='books'?'書店／古書':'採買／景點';return `\u003carticle class="place-card card">\u003cdiv>\u003cspan class="tag pick">主題：${esc(t)}\u003c/span>\u003cspan class="tag">${esc(x.typeLabel)}\u003c/span>\u003cspan class="tag muted">地區：${esc(a?.label||x.area)}\u003c/span>\u003c/div>\u003ch3>${esc(x.name)}\u003c/h3>\u003cp class="why">\u003cb>用途：\u003c/b>${use}\u003c/p>\u003cp class="note">${esc(x.note)}\u003c/p>\u003cdiv>${mlink('📍 Google Maps',x.map||x.name)}\u003c/div>\u003c/article>`;}
function header(active=''){return `\u003cheader class="top">\u003ch1>🌸 樂京都 2026\u003c/h1>\u003cdiv class="small">唯一入口：t202607/index.html｜資料模型：地點物件化\u003c/div>\u003cdiv class="nav">\u003ca class="btn ${active==='index'?'primary':''}" href="index.html">總目錄\u003c/a>\u003ca class="btn" href="itinerary.html">每日行程\u003c/a>\u003ca class="btn" href="transport.html">交通與行李\u003c/a>\u003ca class="btn ${active==='must_go'?'primary':''}" href="theme-must-go.html">本次必去\u003c/a>\u003ca class="btn ${active==='hotel_nearby'?'primary':''}" href="theme-hotel-nearby.html">飯店附近\u003c/a>\u003ca class="btn ${active==='beef_tongue'?'primary':''}" href="theme-beef-tongue.html">牛肉牛舌\u003c/a>\u003ca class="btn ${active==='old_coffee_tea'?'primary':''}" href="theme-old-coffee-tea.html">老咖啡老茶舖\u003c/a>\u003ca class="btn ${active==='books'?'primary':''}" href="type-books.html">書店\u003c/a>\u003c/div>\u003c/header>`;}
function statLine(){return `\u003cdiv class="statbar">\u003cspan>${DB.places.length} 筆地點\u003c/span>\u003cspan>${DB.areas.length} 個地區\u003c/span>\u003cspan>7 種類型\u003c/span>\u003c/div>`;}
function renderIndex(){document.body.insertAdjacentHTML('afterbegin',header('index'));const hero=`\u003csection class="hero-card card">\u003cspan class="tag pick">京都旅遊手帳\u003c/span>\u003ch2>樂京都 2026｜總控制台\u003c/h2>\u003cp class="note">首頁只放入口與判斷。地點內容統一從 \u003cb>KYOTO_PLACES\u003c/b> 物件資料模型渲染；主題頁另由 \u003cb>KYOTO_THEMES\u003c/b> 管理。\u003c/p>${statLine()}\u003cdiv class="quickgrid">\u003ca class="bigbtn" href="itinerary.html">每日行程\u003cspan>7/9–7/13\u003c/span>\u003c/a>\u003ca class="bigbtn" href="transport.html">交通與行李\u003cspan>公開版\u003c/span>\u003c/a>\u003ca class="bigbtn" href="theme-must-go.html">本次必去\u003cspan>老咖啡・建築・書店・茶舖\u003c/span>\u003c/a>\u003ca class="bigbtn" href="theme-hotel-nearby.html">飯店附近\u003cspan>早餐・咖啡・晚餐・錦市場\u003c/span>\u003c/a>\u003ca class="bigbtn" href="theme-beef-tongue.html">牛肉／牛舌\u003cspan>牛舌・燒肉・壽喜燒\u003c/span>\u003c/a>\u003ca class="bigbtn" href="theme-old-coffee-tea.html">老咖啡老茶舖\u003cspan>老喫茶・茶舖・町家茶寮\u003c/span>\u003c/a>\u003ca class="bigbtn" href="type-books.html">書店／古書店\u003cspan>新書・古書・選書\u003c/span>\u003c/a>\u003c/div>\u003c/section>`;const themeRows=Object.values(DB.themes||{}).map(t=>`\u003ca class="card linkcard" href="${THEME_PAGES[t.id]||'#'}">\u003cspan class="tag pick">主題頁\u003c/span>\u003ch3>${esc(t.title)}\u003c/h3>\u003cp class="note">${esc(t.lead)}\u003c/p>\u003c/a>`).join('');const typeRows=TYPE_ORDER.map(k=>`\u003ca class="card linkcard" href="${TYPE_PAGES[k]}">\u003cspan class="tag">依類型\u003c/span>\u003ch3>${label(k)}\u003c/h3>\u003cp class="note">${placesByType(k).length} 筆，先類型再地區。\u003c/p>\u003c/a>`).join('');const areaRows=DB.areas.map(a=>`\u003ca class="card linkcard" href="${a.id}.html">\u003cspan class="tag">依地區\u003c/span>\u003ch3>${a.label}\u003c/h3>\u003cp class="note">${a.title}\u003cbr>${TYPE_ORDER.map(k=>`${label(k)} ${placesByArea(a.id,k).length}`).filter(x=>!x.endsWith(' 0')).join('・')}\u003c/p>\u003c/a>`).join('');document.querySelector('main').innerHTML=`${hero}${themeRows?'\u003ch2 id="themes">主題頁\u003c/h2>\u003cdiv class="grid">'+themeRows+'\u003c/div>':''}\u003ch2 id="types">依類型找\u003c/h2>\u003cdiv class="grid">${typeRows}\u003c/div>\u003ch2 id="areas">依地區找\u003c/h2>\u003cdiv class="grid">${areaRows}\u003c/div>`;}
function renderArea(id){const area=DB.areas.find(a=>a.id===id);document.body.insertAdjacentHTML('afterbegin',header(id));const keys=typeListForArea(id);const all=keys.flatMap(k=>placesByArea(id,k));const featured=sortPlaces(all).filter((p,i)=>p.priority==='high'||i<5).slice(0,5);const nav=`\u003cdiv class="nav localnav">${keys.map(k=>`\u003ca class="btn" href="#${k}">${label(k)} ${placesByArea(id,k).length}\u003c/a>`).join('')}\u003c/div>`;const sections=keys.map(k=>`\u003csection class="typeblock" id="${k}">\u003ch2>${label(k)} \u003cspan class="small">${placesByArea(id,k).length} 筆\u003c/span>\u003c/h2>\u003cdiv class="placegrid">${placesByArea(id,k).map(placeCard).join('')}\u003c/div>\u003c/section>`).join('');document.querySelector('main').innerHTML=`\u003csection class="hero-card card">\u003cspan class="tag pick">地區\u003c/span>\u003ch2>${esc(area.title)}\u003c/h2>\u003cp class="note">${esc(area.lead||'本區地點依類型分組；同一地點可同時出現在老舖、建築、書店等分類。')}\u003c/p>${statLine()}\u003ca class="map" href="index.html">回總目錄\u003c/a>\u003c/section>\u003ch2>本區優先\u003c/h2>\u003cdiv class="placegrid featured">${featured.map(placeCard).join('')}\u003c/div>${nav}${sections}\u003ca class="back" href="#">↑ 上方\u003c/a>`;}
function groupByArea(list){return DB.areas.map(a=>[a,sortPlaces(list.filter(p=>p.area===a.id))]).filter(([,items])=>items.length);}
function renderType(kind){if(kind==='books')return renderBooks();document.body.insertAdjacentHTML('afterbegin',header(kind));const list=placesByType(kind);const groups=groupByArea(list);const nav=`\u003cdiv class="nav localnav">${groups.map(([a,items])=>`\u003ca class="btn" href="#${a.id}">${a.label} ${items.length}\u003c/a>`).join('')}\u003c/div>`;const sections=groups.map(([a,items])=>`\u003csection class="typeblock" id="${a.id}">\u003ch2>${a.label} \u003cspan class="small">${items.length} 筆\u003c/span>\u003c/h2>\u003cdiv class="placegrid">${items.map(placeCard).join('')}\u003c/div>\u003c/section>`).join('');document.querySelector('main').innerHTML=`\u003csection class="hero-card card">\u003cspan class="tag pick">依類型找\u003c/span>\u003ch2>${label(kind)}\u003c/h2>\u003cp class="note">先看類型，再依地區分組。內容可與地區頁重複，因為同一個地點可能同時是老舖、建築或景點。\u003c/p>\u003cdiv class="statbar">\u003cspan>${list.length} 筆\u003c/span>\u003cspan>${groups.length} 區\u003c/span>\u003c/div>\u003ca class="map" href="index.html">回總目錄\u003c/a>\u003c/section>${nav}${sections}\u003ca class="back" href="#">↑ 上方\u003c/a>`;}
function routeCard(r){return `\u003carticle class="route-card card">\u003cspan class="tag pick">實用路線\u003c/span>\u003ch3>${r.title}\u003c/h3>\u003cdiv class="routechips">${r.items.map((x,i)=>`\u003cspan>${i+1}. ${x}\u003c/span>`).join('')}\u003c/div>\u003cp class="note">當成移動順序參考，不代表每一站都必進。\u003c/p>\u003c/article>`;}
function priorityCard(g){return `\u003carticle class="route-card card">\u003cspan class="tag pick">優先\u003c/span>\u003ch3>${g.title}\u003c/h3>\u003cdiv>${g.items.map(x=>mlink(x,x)).join('')}\u003c/div>\u003c/article>`;}
function renderBooks(){document.body.insertAdjacentHTML('afterbegin',header('books'));const d=DB;const themeBookItems=sortPlaces(d.places.filter(p=>p.category==='books'&&!p.bookSection));const priority=`\u003ch2>${d.bookPriority.title}\u003c/h2>\u003cdiv class="grid">${d.bookPriority.groups.map(priorityCard).join('')}\u003c/div>`;const routes=`\u003ch2>你的實用路線\u003c/h2>\u003cdiv class="grid">${d.bookRoutes.map(routeCard).join('')}\u003c/div>`;const nav=`\u003cdiv class="nav localnav">${d.bookSections.map(s=>`\u003ca class="btn" href="#${s.id}">${s.title}\u003c/a>`).join('')}${themeBookItems.length?`\u003ca class="btn" href="#theme-books">本次必去 ${themeBookItems.length}\u003c/a>`:''}\u003c/div>`;const sections=d.bookSections.map(s=>{const items=sortPlaces(d.places.filter(p=>p.category==='books'&&p.bookSection===s.id));return `\u003csection class="typeblock" id="${s.id}">\u003ch2>${s.title} \u003cspan class="small">${items.length} 筆\u003c/span>\u003c/h2>\u003cdiv class="card">\u003cp class="note">${s.lead}\u003c/p>\u003c/div>\u003cdiv class="placegrid">${items.map(placeCard).join('')}\u003c/div>\u003c/section>`;}).join('');const themeBooks=themeBookItems.length?`\u003csection class="typeblock" id="theme-books">\u003ch2>本次必去書店 \u003cspan class="small">${themeBookItems.length} 筆\u003c/span>\u003c/h2>\u003cdiv class="card">\u003cp class="note">由主題頁「本次必去」合併進來，確保主題書店也能在書店分類頁看到。\u003c/p>\u003c/div>\u003cdiv class="placegrid">${themeBookItems.map(placeCard).join('')}\u003c/div>\u003c/section>`:'';document.querySelector('main').innerHTML=`\u003csection class="hero-card card">\u003cspan class="tag pick">書店正本資料\u003c/span>\u003ch2>京都書店／古書店\u003c/h2>\u003cp class="note">依京都觀光會走到的區域整理新書、古書、選書店。這頁由統一地點物件資料渲染。\u003c/p>\u003cdiv class="statbar">\u003cspan>${placesByType('books').length} 筆書店\u003c/span>\u003cspan>${d.bookSections.length} 個書店區\u003c/span>\u003c/div>\u003ca class="map" href="index.html">回總目錄\u003c/a>\u003c/section>${nav}${priority}${routes}${sections}${themeBooks}\u003ca class="back" href="#">↑ 上方\u003c/a>`;}
function renderTheme(id){const t=DB.themes?.[id];document.body.insertAdjacentHTML('afterbegin',header(id));if(!t){document.querySelector('main').innerHTML='\u003csection class="card">\u003ch2>找不到主題資料\u003c/h2>\u003c/section>';return;}const total=t.sections.reduce((n,s)=>n+s.items.length,0);const nav=`\u003cdiv class="nav localnav">${t.sections.map(s=>`\u003ca class="btn" href="#${s.id}">${s.title} ${s.items.length}\u003c/a>`).join('')}\u003c/div>`;const sections=t.sections.map(s=>`\u003csection class="typeblock" id="${s.id}">\u003ch2>${s.title} \u003cspan class="small">${s.items.length} 筆\u003c/span>\u003c/h2>\u003cdiv class="card">\u003cp class="note">${s.lead}\u003c/p>\u003c/div>\u003cdiv class="placegrid">${s.items.map(x=>themeItemCard(x,t.title)).join('')}\u003c/div>\u003c/section>`).join('');document.querySelector('main').innerHTML=`\u003csection class="hero-card card">\u003cspan class="tag pick">主題頁\u003c/span>\u003ch2>${t.title}\u003c/h2>\u003cp class="note">${t.lead}\u003c/p>\u003cdiv class="statbar">\u003cspan>${total} 筆\u003c/span>\u003cspan>${t.sections.length} 類\u003c/span>\u003cspan>基準：${t.base.name}\u003c/span>\u003c/div>${mlink('📍 地圖基準點',t.base.map)}\u003c/section>${nav}${sections}\u003ca class="back" href="#">↑ 上方\u003c/a>`;}
function boot(){if(!DB){document.querySelector('main').innerHTML='\u003cdiv class="card">\u003ch2>資料尚未載入\u003c/h2>\u003c/div>';return;}if(window.PAGE_THEME)return renderTheme(window.PAGE_THEME);if(window.PAGE_AREA)return renderArea(window.PAGE_AREA);if(window.PAGE_KIND)return renderType(window.PAGE_KIND);renderIndex();}
document.addEventListener('DOMContentLoaded',boot);
