const AREAS=[['karasuma','四條烏丸'],['sanjo','烏丸御池'],['kawaramachi','河原町'],['pontocho','先斗町'],['gion','祇園清水'],['okazaki','岡崎銀閣'],['rakuhoku','洛北大原'],['rakusai','洛西嵐山'],['rakunan','洛南伏見'],['uji','宇治'],['nara','奈良公園'],['nara_far','奈良遠郊']];
const TYPE_LABEL={spots:'景點',food:'餐廳',cafe:'咖啡廳／茶店',shop:'商店／老舖'};
const map=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
function cls(t){return (t||'').includes('飯店')?'near':((t||'').includes('老舖')||(t||'').includes('老屋')||(t||'').includes('町家')?'old':((t||'').includes('洋風')||(t||'').includes('近代')||(t||'').includes('昭和')||(t||'').includes('大正')||(t||'').includes('明治')?'western':''));}
function item(s){const [n,t,d]=s.split('|');return `<div class="card"><span class="tag ${cls(t)}">${t||'地點'}</span><h3>${n}</h3><p class="note">${d||''}</p><a class="map" target="_blank" href="${map(n)}">📍 Google Maps</a></div>`;}
function header(active){return `<header class="top"><h1>🌸 樂京都 2026</h1><div class="small">多頁版｜地區 → 類型</div><div class="nav"><a class="btn" href="index.html">總目錄</a><a class="btn" href="itinerary.html">每日行程</a>${AREAS.map(([id,label])=>`<a class="btn ${id===active?'primary':''}" href="${id}.html">${label}</a>`).join('')}</div></header>`;}
function renderArea(id){const a=KYOTO_AREAS[id];document.body.insertAdjacentHTML('afterbegin',header(id));const total=['spots','food','cafe','shop'].reduce((n,k)=>n+(a[k]?.length||0),0);document.querySelector('main').innerHTML=`<h2>${a.title}</h2><p class="note">${a.lead}</p><div class="card"><span class="tag">本區 ${total} 筆</span><a class="map" href="../t202607.html">回入口</a></div>${['spots','food','cafe','shop'].map(k=>`<section class="typeblock" id="${k}"><h2>${TYPE_LABEL[k]} <span class="small">${a[k]?.length||0} 筆</span></h2>${(a[k]||[]).map(item).join('')}</section>`).join('')}<a class="back" href="#">↑ 上方</a>`;}
function renderIndex(){document.body.insertAdjacentHTML('afterbegin',header(''));const rows=AREAS.map(([id,label])=>{const a=KYOTO_AREAS[id];const total=['spots','food','cafe','shop'].reduce((n,k)=>n+(a[k]?.length||0),0);return `<a class="card" style="display:block;text-decoration:none;color:inherit" href="${id}.html"><span class="tag">${total} 筆</span><h3>${label}</h3><p class="note">${a.title}<br>${a.lead}</p></a>`}).join('');document.querySelector('main').innerHTML=`<h2>地區總目錄</h2><div class="card"><b>入口邏輯</b><p class="note">每日行程獨立一頁；地點資料分成 12 個地區頁。每個地區頁再分景點、餐廳、咖啡廳／茶店、商店／老舖。</p></div><div class="grid">${rows}</div>`;}
function renderItinerary(){document.body.insertAdjacentHTML('afterbegin',header('itinerary'));const days=[['7/9｜關西空港・奈良・京都入住',['關西空港通關與行李配送','南海難波轉近鐵奈良','奈良公園・東大寺・春日大社','傍晚回京都入住']],['7/10｜清水寺・東山・祇園祭',['五條坂・茶碗坂・清水寺','清水燒・二年坂・三年坂','高台寺・圓德院・八坂神社','京都高島屋與四條大橋神輿洗']],['7/11｜宇治',['京都到宇治','中村藤吉・伊藤久右衛門・辻利・三星園','平等院鳳凰堂','宇治川・宇治橋']],['7/12｜南禪寺・老舖・三條近代建築線',['南禪寺・水路閣・天授庵','平安神宮神苑','一保堂・鳩居堂・宮脇賣扇庵','新風館・中京郵便局・京都文化博物館別館']]];document.querySelector('main').innerHTML=`<h2>每日行程</h2><div class="card"><span class="tag">先維持</span><p class="note">這頁先把被壞掉的每日行程獨立出來。之後要細改 D1-D4，不會影響地區資料庫。</p></div>${days.map(d=>`<section><h2>${d[0]}</h2><div class="card">${d[1].map(x=>`<div class="map">${x}</div>`).join('')}</div></section>`).join('')}`;}
document.addEventListener('DOMContentLoaded',()=>{if(window.PAGE_TYPE==='index')renderIndex();else if(window.PAGE_TYPE==='itinerary')renderItinerary();else renderArea(window.PAGE_AREA);});