const DB=window.KYOTO_PLACES;
const T=DB.themes?.must_go;
const TYPE_ORDER=['books','food','drinks','shops','sights'];
const map=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const label=k=>DB.categories[k]?.label||k;
const mlink=(txt,q)=>`\u003ca class="map" target="_blank" rel="noopener" href="${map(q||txt)}">${txt}\u003c/a>`;
function header(){return `\u003cheader class="top">\u003ch1>🌸 樂京都 2026\u003c/h1>\u003cdiv class="small">唯一入口：t202607/index.html｜資料模型：KYOTO_THEMES.must_go → KYOTO_PLACES\u003c/div>\u003cdiv class="nav">\u003ca class="btn" href="index.html">總目錄\u003c/a>\u003ca class="btn" href="itinerary.html">每日行程\u003c/a>\u003ca class="btn" href="transport.html">交通與行李\u003c/a>\u003ca class="btn primary" href="theme-must-go.html">本次必去\u003c/a>\u003ca class="btn" href="theme-hotel-nearby.html">飯店附近\u003c/a>\u003ca class="btn" href="theme-beef-tongue.html">牛肉牛舌\u003c/a>\u003ca class="btn" href="theme-old-coffee-tea.html">老咖啡老茶舖\u003c/a>\u003ca class="btn" href="type-books.html">書店\u003c/a>\u003c/div>\u003c/header>`;}
function items(){return (T.sections||[]).flatMap(s=>(s.items||[]).map(x=>({...x,sectionTitle:s.title})));}
function card(x){const a=DB.areas.find(v=>v.id===x.area);const use=x.category==='food'?'正餐／西餐':x.category==='drinks'?'咖啡／茶':x.category==='books'?'書店／古書':'景點／建築';return `\u003carticle class="place-card card">\u003cdiv>\u003cspan class="tag pick">主題：本次必去\u003c/span>\u003cspan class="tag">${x.typeLabel}\u003c/span>\u003cspan class="tag muted">地區：${a?.label||x.area}\u003c/span>\u003c/div>\u003ch3>${x.name}\u003c/h3>\u003cp class="why">\u003cb>用途：\u003c/b>${use}\u003c/p>\u003cp class="note">${x.note}\u003c/p>\u003cdiv>${mlink('📍 Google Maps',x.map||x.name)}\u003c/div>\u003c/article>`;}
function boot(){if(!DB||!T){document.querySelector('main').innerHTML='\u003csection class="card">\u003ch2>資料尚未載入\u003c/h2>\u003c/section>';return;}document.body.insertAdjacentHTML('afterbegin',header());const xs=items();const areaGroups=DB.areas.map(a=>[a,xs.filter(x=>x.area===a.id)]).filter(([,v])=>v.length);const typeGroups=TYPE_ORDER.filter(k=>xs.some(x=>x.category===k)).map(k=>[k,xs.filter(x=>x.category===k)]);const areaNav=areaGroups.map(([a,v])=>`\u003ca class="btn" href="#area-${a.id}">${a.label} ${v.length}\u003c/a>`).join('');const typeNav=typeGroups.map(([k,v])=>`\u003ca class="btn" href="#type-${k}">${label(k)} ${v.length}\u003c/a>`).join('');const areaSections=areaGroups.map(([a,v])=>`\u003csection class="typeblock" id="area-${a.id}">\u003ch2>${a.label} \u003cspan class="small">${v.length} 筆\u003c/span>\u003c/h2>\u003cdiv class="placegrid">${v.map(card).join('')}\u003c/div>\u003c/section>`).join('');const typeSections=typeGroups.map(([k,v])=>`\u003csection class="typeblock" id="type-${k}">\u003ch2>${label(k)} \u003cspan class="small">${v.length} 筆\u003c/span>\u003c/h2>\u003cdiv class="placegrid">${v.map(card).join('')}\u003c/div>\u003c/section>`).join('');document.querySelector('main').innerHTML=`\u003csection class="hero-card card">\u003cspan class="tag pick">主題頁\u003c/span>\u003ch2>${T.title}\u003c/h2>\u003cp class="note">${T.lead}\u003c/p>\u003cdiv class="statbar">\u003cspan>${xs.length} 筆\u003c/span>\u003cspan>${areaGroups.length} 個地區\u003c/span>\u003cspan>${typeGroups.length} 種類型\u003c/span>\u003c/div>${mlink('📍 地圖基準：四条烏丸',T.base.map)}\u003c/section>\u003ch2>依地區分類\u003c/h2>\u003cdiv class="nav localnav">${areaNav}\u003c/div>${areaSections}\u003ch2>依類型分類\u003c/h2>\u003cdiv class="nav localnav">${typeNav}\u003c/div>${typeSections}\u003ca class="back" href="#">↑ 上方\u003c/a>`;}
document.addEventListener('DOMContentLoaded',boot);
