const FLIGHTS=window.KYOTO_ITINERARY_FLIGHTS||{};
const LUGGAGE=window.KYOTO_ITINERARY_LUGGAGE||{};
const map=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const ext=link=>`<a class="flight-link" target="_blank" rel="noopener" href="${link.url}">${link.label}</a>`;
function mapLink(label,q){return `<a class="map" target="_blank" rel="noopener" href="${map(q)}">${label}</a>`;}
function flightCard(f){return `<article class="flight-card"><div class="flight-top"><div><div class="flight-kicker">✈️ ${f.direction}｜${f.airline}</div><div class="flight-no">${f.flightNo}</div><div class="flight-route">${f.route}</div><span class="flight-terminal">${f.terminal}</span></div><div class="flight-time">${f.date}<br>${f.time}</div></div><p class="flight-note">${f.note}</p><div class="flight-links">${f.links.map(ext).join('')}</div></article>`;}
function luggageCard(x){return `<article class="flight-card"><div class="flight-top"><div><div class="flight-kicker">🧳 Airporter／JALABC</div><div class="flight-no">${x.title}</div><div class="flight-route">${x.location}</div><span class="flight-terminal">營業 ${x.time}</span></div><div class="flight-time">${x.date}<br>2 件大行李</div></div><p class="flight-note">${x.action}<br>${x.note}</p><div class="flight-links">${x.links.map(ext).join('')}</div></article>`;}
function row(time,note,pills){return `<div class="row"><div class="time">${time}</div><p class="note">${note}</p><div>${pills.map(x=>`<span class="pill">${x}</span>`).join('')}</div></div>`;}
function renderTransport(){document.body.insertAdjacentHTML('afterbegin',`<header class="top"><h1>🚆 交通與行李</h1><div class="small">公開版：只放時間、路線、航班連結、行李櫃檯與集合資訊；不放 PNR、姓名、票號、單號、驗證碼、住家地址。</div><div class="nav"><a class="btn" href="index.html">總目錄</a><a class="btn" href="itinerary.html">每日行程</a><a class="btn primary" href="transport.html">交通與行李</a></div></header>`);
const flights=[...(FLIGHTS.d1||[]),...(FLIGHTS.d6||[])].map(flightCard).join('');
const luggage=(LUGGAGE.d1||[]).map(luggageCard).join('');
document.querySelector('main').innerHTML=`<section class="card"><span class="tag safe">公開安全版</span><h2>不放上網頁的資料</h2><p class="note">Booking ID、PNR、人名、票號、券票號碼、接送單號、驗證碼、住家完整地址、付款卡號、QR 票券連結。</p></section><h2>航班動態</h2><section class="grid2">${flights}</section><h2>Airporter／行李櫃檯</h2><section>${luggage}</section><h2>去程｜7/8–7/9</h2><section class="card timeline">${row('7/8 22:55｜住家出發 → 桃園機場第一航廈','已安排去程機場接送。公開頁只寫「住家」與「桃園機場第一航廈」，不放完整地址、單號與驗證碼。',['全鋒機場接送','桃園機場 T1','不公開住家地址'])}${row('7/9 02:30–06:05｜Jetstar Japan GK50｜TPE → KIX','去程航班為 Jetstar Japan GK50，02:30 從台北桃園出發，06:05 抵達關西國際機場。抵達後先入境、領行李、出關。',['TPE 桃園機場','KIX 關西空港','手提 1 件 7kg／人','託運 30kg × 1'])}${row('7/9 08:00 前｜AirPorter 行李配送','抵達 KIX 後，將 2 件大行李交給 Airporter。寄放櫃檯是 KIX Terminal 1 的 1F JALABC Arrival Counter。',['KIX T1 1F','JALABC Arrival Counter','行李 2 件','送達 ibis Styles Kyoto Shijo','20:00 送達'])}${row('7/9 白天｜關西空港 → 奈良 → 京都','大行李送走後，輕裝前往奈良。交通主線是關西空港到難波，再轉近鐵到奈良；傍晚從奈良回京都，最後到四条烏丸飯店 check in。',['關西空港','難波','近鐵奈良','京都','四条烏丸'])}</section><h2>住宿與行李基準</h2><section class="card"><h3>ibis Styles Kyoto Shijo</h3><p class="note">住宿期間為 2026-07-09 至 2026-07-14。公開頁只放飯店名稱與住宿日期，不放訂單編號、參照編號、房客姓名、付款資訊。</p>${mapLink('📍 Google Maps','ibis Styles Kyoto Shijo')}</section><h2>回程｜7/14</h2><section class="card timeline">${row('14:30–15:50｜Haruka No.35｜京都 → 關西空港','回程搭乘 Haruka No.35，14:30 從京都出發，15:50 抵達關西空港。已預約指定席。公開頁不放座位、券票號碼與 QR 電子票連結。',['京都 14:30','關西空港 15:50','指定席已預約','WEST QR 電子票'])}${row('18:30–20:30｜EVA Air BR129｜KIX → TPE','回程航班為 EVA Air BR129，18:30 從關西國際機場出發，20:30 抵達台北桃園。公開頁不放訂位代號、乘客姓名與票務資料。',['KIX 關西空港','TPE 桃園機場','手提 1 件 7kg／人','託運 1 件／人'])}${row('20:30 後｜桃園機場第二航廈 → 住家','已安排回程機場接送。公開頁只寫「桃園機場第二航廈」與「住家」，不放完整地址、單號與驗證碼。',['全鋒機場接送','桃園機場 T2','不公開住家地址'])}</section><h2>待處理</h2><section class="grid2"><div class="card"><span class="tag warn">尚未處理</span><h3>兒童 ICOCA</h3><p class="note">待購買、領取或確認使用方式。</p></div><div class="card"><span class="tag warn">尚未處理</span><h3>旅遊保險</h3><p class="note">預計處理旅遊保險。公開頁不放保單號與個資。</p></div></section>`;}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',renderTransport);else renderTransport();
